INSERT INTO CATEGORIES(ID,NAME) values(1,'GENERAL LABOUR'),(2,'SKILLED TRADE'),(3,'ART'),(4,'TECHNICAL');
INSERT INTO SUBCATEGORIES(ID, NAME, FK_CATEGORY_ID) VALUES(1,'ROOFING', 2),
						(2,'LANDSCAPING',1),(3,'CHOREOGRAPHER',3),
						(4,'WELDER',2),(5,'ENGINEER',4);

INSERT INTO COUNTRY VALUES(1, 'INDIA');
INSERT INTO STATE(STATE_ID, STATE_NAME, FK_COUNTRY_ID) VALUES(1, 'GUJARAT', 1), (2, 'MAHARASTRA', 1), (3,'TELANGANA', 1);
INSERT INTO CITY(CITY_ID, CITY_NAME, FK_STATE_ID) VALUES(1, 'BARODA', 1), (2,'AHMEDABAD', 1),(3, 'SURAT',1),
										(4,'PUNE',2),(5,'MUMBAI',2),(6,'JALGAON',2),
										(7,'BANGALORE', 3),(8,'CHENNAI', 3);
INSERT INTO AREA(AREA_ID, AREA_NAME, FK_CITY_ID) VALUES(1,'MANJALPUR',1), (2,'SAMA',1),
										(3,'ELLISBRIDGE',2),(4,'CORPORATEROAD',2),
										(5,'PUNE',4),(6,'BARODA',1);
